"""
agents/ops_briefing_agent.py
==============================
Daily Ops Briefing Agent — synthesizes wildfire ops + PSPS situation
into a structured Markdown briefing for the ExfSafeGrid Ops view.
Stores output in: daily_briefings table
Run standalone:
  python agents/ops_briefing_agent.py
  python agents/ops_briefing_agent.py --date 2025-07-15 --overwrite
"""
import argparse
import json
import logging
import sys
from datetime import date, timedelta
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).parent.parent))

import anthropic
from sqlalchemy import text
from sqlalchemy.orm import Session

from config.database import SessionLocal
from config.settings import settings

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are a senior Wildfire Operations & PSPS Planning Analyst at a Western utility.
Produce a concise, actionable morning briefing for the ops team.
Use this exact Markdown structure:

# Wildfire Ops & PSPS Daily Briefing — {date}

## Situation Overview
[2-3 sentence executive summary of current wildfire threat environment]

## 🔴 Highest-Risk Circuits (Next 24h)
[Bullet list of top circuits at HIGH or CRITICAL ignition spike risk. Include circuit_id, PSA, risk score, key driver.]

## 🔥 Active Fire Threats
[Bullet list of significant active fires. Include name, acres, containment%, state, proximity.]

## 📅 7-Day Outlook Highlights
[PSAs with Above Normal+ potential in Day 1–3. Note any escalations.]

## ⚡ PSPS Watch
[Circuits to monitor for potential de-energization in next 24–72h. Flag customer impact.]

## ✅ Recommended Actions
[3–5 specific, numbered operational actions for today]

---
*Generated by ExfSafeGrid Ops Briefing Agent | {date}*

Be direct, use ops language, flag CRITICAL situations with ⚠️. Keep under 600 words.
"""


def _gather_context(db: Session, briefing_date: date) -> dict:
    active_incidents = db.execute(text("""
        SELECT incident_name, state, ROUND(acres_burned) AS acres,
               containment_pct, psa_id
        FROM incidents WHERE is_active = TRUE
        ORDER BY acres_burned DESC NULLS LAST LIMIT 12
    """)).fetchall()

    top_risk_circuits = db.execute(text("""
        SELECT mp.circuit_id, mp.risk_bucket, ROUND(mp.prob_score::NUMERIC, 3) AS prob,
               uc.psa_id, uc.hftd_tier, uc.customer_count, uc.critical_customers, uc.county
        FROM model_predictions mp
        JOIN utility_circuits uc ON uc.circuit_id = mp.circuit_id
        WHERE mp.model_name = 'ignition_spike'
          AND mp.horizon_label = '24h'
          AND mp.prediction_date = :today
          AND mp.risk_bucket IN ('HIGH', 'CRITICAL')
        ORDER BY mp.prob_score DESC LIMIT 10
    """), {"today": str(briefing_date)}).fetchall()

    elevated_outlooks = db.execute(text("""
        SELECT psa_id, period_label, fire_potential_label, fire_potential
        FROM psa_outlook
        WHERE outlook_type = '7day'
          AND forecast_date = :today
          AND period_label IN ('Day1', 'Day2', 'Day3')
          AND fire_potential >= 3
        ORDER BY fire_potential DESC, period_label ASC LIMIT 20
    """), {"today": str(briefing_date)}).fetchall()

    recent_psps = db.execute(text("""
        SELECT circuit_id, start_time, customers_off, trigger_reason, is_active
        FROM psps_events
        WHERE start_time >= :since
        ORDER BY start_time DESC LIMIT 8
    """), {"since": str(briefing_date - timedelta(days=3))}).fetchall()

    return {
        "briefing_date": str(briefing_date),
        "active_incidents": [dict(r._mapping) for r in active_incidents],
        "top_risk_circuits": [dict(r._mapping) for r in top_risk_circuits],
        "elevated_outlooks": [dict(r._mapping) for r in elevated_outlooks],
        "recent_psps_events": [dict(r._mapping) for r in recent_psps],
        "n_incidents": len(active_incidents),
        "n_critical": sum(1 for r in top_risk_circuits if dict(r._mapping)["risk_bucket"] == "CRITICAL"),
    }


def run(db: Optional[Session] = None, briefing_date: Optional[date] = None, overwrite: bool = False) -> dict:
    if briefing_date is None:
        briefing_date = date.today()

    if not settings.ANTHROPIC_API_KEY:
        return {"status": "error", "error": "ANTHROPIC_API_KEY not configured"}

    own_db = db is None
    if own_db:
        db = SessionLocal()

    try:
        if not overwrite:
            existing = db.execute(
                text("SELECT markdown_text FROM daily_briefings WHERE briefing_date = :d"),
                {"d": str(briefing_date)},
            ).fetchone()
            if existing:
                return {"status": "cached", "briefing_date": str(briefing_date), "markdown_text": existing[0]}

        ctx = _gather_context(db, briefing_date)

        user_msg = f"""Generate the daily briefing for {briefing_date}.
ACTIVE INCIDENTS ({ctx['n_incidents']}): {json.dumps(ctx['active_incidents'], default=str)}
HIGH/CRITICAL CIRCUITS (24h): {json.dumps(ctx['top_risk_circuits'], default=str)}
ELEVATED OUTLOOKS (Day1-3): {json.dumps(ctx['elevated_outlooks'], default=str)}
RECENT PSPS: {json.dumps(ctx['recent_psps_events'], default=str)}"""

        client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)
        msg = client.messages.create(
            model=settings.CLAUDE_MODEL,
            max_tokens=1500,
            system=SYSTEM_PROMPT.replace("{date}", str(briefing_date)),
            messages=[{"role": "user", "content": user_msg}],
        )

        md = msg.content[0].text
        tokens = msg.usage.input_tokens + msg.usage.output_tokens

        db.execute(text("""
            INSERT INTO daily_briefings (briefing_date, markdown_text, structured_data, model_used, tokens_used)
            VALUES (:d, :md, CAST(:ctx AS JSONB), :model, :tok)
            ON CONFLICT (briefing_date) DO UPDATE SET
                markdown_text = EXCLUDED.markdown_text,
                structured_data = EXCLUDED.structured_data,
                tokens_used = EXCLUDED.tokens_used,
                created_at = NOW()
        """), {"d": str(briefing_date), "md": md, "ctx": json.dumps(ctx, default=str),
               "model": settings.CLAUDE_MODEL, "tok": tokens})
        db.commit()

        logger.info("✓ Briefing %s: %d tokens, %d critical circuits", briefing_date, tokens, ctx["n_critical"])
        return {"status": "success", "briefing_date": str(briefing_date), "markdown_text": md,
                "tokens_used": tokens, "n_critical": ctx["n_critical"]}
    except Exception as exc:
        logger.exception("Ops briefing failed: %s", exc)
        return {"status": "error", "error": str(exc)}
    finally:
        if own_db:
            db.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--date", default=None)
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--log-level", default="INFO")
    args = parser.parse_args()
    logging.basicConfig(level=getattr(logging, args.log_level), format="%(asctime)s %(levelname)s %(message)s")
    d = date.fromisoformat(args.date) if args.date else None
    r = run(briefing_date=d, overwrite=args.overwrite)
    print(r.get("markdown_text") or r)
